/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ta.johan.layout;

import com.ta.johan.control.control_alternatif;
import com.ta.johan.control.control_home;
import com.ta.johan.control.control_kriteria;
import com.ta.johan.control.control_perhitungan;
import com.ta.johan.control.control_subkriteria;
import com.ta.johan.control.control_user;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.applet.Main;

/**
 *
 * @author Irawan Papang S
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    control_kriteria controlkriteria;
    control_subkriteria controlsubkriteria;
    control_alternatif controlalternatif;
    control_perhitungan controlperhitungan;
    control_user controluser;
    control_home controlhome;

    kriteria k;
    subkriteria s;
    alternatif a;
    perhitungan p;
    user u;
    home h;

    public main() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

        controlkriteria = new control_kriteria();
        controlsubkriteria = new control_subkriteria();
        controlalternatif = new control_alternatif();
        controlperhitungan = new control_perhitungan();
        controluser = new control_user();
        controlhome = new control_home();

        a = new alternatif();
        s = new subkriteria();
        k = new kriteria();
        p = new perhitungan();
        u = new user();
        h = new home();
    }

    public void panggil(String userlogin) {
        switch (userlogin) {
            case "User":
                enable(true);

                buttonImageReflection2.doClick();
                jLabel1.setText("User");

                break;
            case "Admin":
                enable(false);

                buttonImageReflection2.doClick();
                jLabel1.setText("Admin");

                break;
        }
    }

    public void enable(boolean status) {

        buttonImageReflection1.setVisible(!status);
        jMenuItem8.setVisible(!status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneGambarHome1 = new com.ta.johan.background.JDesktopPaneGambarHome();
        buttonImageReflection2 = new usu.widget.glass.ButtonImageReflection();
        buttonImageReflection4 = new usu.widget.glass.ButtonImageReflection();
        buttonImageReflection5 = new usu.widget.glass.ButtonImageReflection();
        buttonImageReflection3 = new usu.widget.glass.ButtonImageReflection();
        buttonImageReflection1 = new usu.widget.glass.ButtonImageReflection();
        jDesktopPanetransparan1 = new com.ta.johan.background.JDesktopPanetransparan();
        jSeparator1 = new javax.swing.JSeparator();
        buttonImageReflection6 = new usu.widget.glass.ButtonImageReflection();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SISTEM PENDUKUNG KEPUTUSAN PEMILIHAN MARKETPLACE BERDASARKAN KEBUTUHAN PENGGUNA MENGGUNAKAN METODE ANALYTICAL HIERARCHY PROCESS (AHP)");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close(evt);
            }
        });

        buttonImageReflection2.setForeground(new java.awt.Color(0, 0, 0));
        buttonImageReflection2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_118770_home_icon_512px.png"))); // NOI18N
        buttonImageReflection2.setText("BERANDA");
        buttonImageReflection2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImageReflection2ActionPerformed(evt);
            }
        });

        buttonImageReflection4.setForeground(new java.awt.Color(0, 0, 0));
        buttonImageReflection4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clipboard.png"))); // NOI18N
        buttonImageReflection4.setText("KRITERIA");
        buttonImageReflection4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImageReflection4ActionPerformed(evt);
            }
        });

        buttonImageReflection5.setForeground(new java.awt.Color(0, 0, 0));
        buttonImageReflection5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/list.png"))); // NOI18N
        buttonImageReflection5.setText("SUBKRITERIA");
        buttonImageReflection5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImageReflection5ActionPerformed(evt);
            }
        });

        buttonImageReflection3.setForeground(new java.awt.Color(0, 0, 0));
        buttonImageReflection3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1461876790_stock_task-assigned-to copy.png"))); // NOI18N
        buttonImageReflection3.setText("MARKETPLACE");
        buttonImageReflection3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImageReflection3ActionPerformed(evt);
            }
        });

        buttonImageReflection1.setForeground(new java.awt.Color(0, 0, 0));
        buttonImageReflection1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/question.png"))); // NOI18N
        buttonImageReflection1.setText("USER");
        buttonImageReflection1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImageReflection1ActionPerformed(evt);
            }
        });

        jDesktopPanetransparan1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jDesktopPanetransparan1.setForeground(new java.awt.Color(0, 0, 0));
        jDesktopPanetransparan1.setOpaque(false);
        jDesktopPanetransparan1.setLayout(new java.awt.BorderLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        buttonImageReflection6.setForeground(new java.awt.Color(0, 0, 0));
        buttonImageReflection6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1493393979_Finance_finance_caaslculator.png"))); // NOI18N
        buttonImageReflection6.setText("PERHITUNGAN");
        buttonImageReflection6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImageReflection6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("jLabel1");

        jDesktopPaneGambarHome1.setLayer(buttonImageReflection2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneGambarHome1.setLayer(buttonImageReflection4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneGambarHome1.setLayer(buttonImageReflection5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneGambarHome1.setLayer(buttonImageReflection3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneGambarHome1.setLayer(buttonImageReflection1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneGambarHome1.setLayer(jDesktopPanetransparan1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneGambarHome1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneGambarHome1.setLayer(buttonImageReflection6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneGambarHome1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneGambarHome1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneGambarHome1Layout = new javax.swing.GroupLayout(jDesktopPaneGambarHome1);
        jDesktopPaneGambarHome1.setLayout(jDesktopPaneGambarHome1Layout);
        jDesktopPaneGambarHome1Layout.setHorizontalGroup(
            jDesktopPaneGambarHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneGambarHome1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPaneGambarHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPanetransparan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jDesktopPaneGambarHome1Layout.createSequentialGroup()
                        .addComponent(buttonImageReflection2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonImageReflection4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonImageReflection5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonImageReflection3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonImageReflection6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonImageReflection1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneGambarHome1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        jDesktopPaneGambarHome1Layout.setVerticalGroup(
            jDesktopPaneGambarHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneGambarHome1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPaneGambarHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonImageReflection5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonImageReflection6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonImageReflection2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonImageReflection4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonImageReflection3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonImageReflection1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPaneGambarHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPanetransparan1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jDesktopPaneGambarHome1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setOpaque(false);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1496415864_gnome-session-logout.png"))); // NOI18N
        jMenuItem1.setText("Login");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1493449455_Log Out.png"))); // NOI18N
        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Home");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_118770_home_icon_512px1.png"))); // NOI18N
        jMenuItem6.setText("Beranda");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Data");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clipboard1.png"))); // NOI18N
        jMenuItem3.setText("Kriteria");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/list1.png"))); // NOI18N
        jMenuItem4.setText("Subkriteria");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1461876790_stock_task-assigned-to copy1.png"))); // NOI18N
        jMenuItem5.setText("Alternatif");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/question1.png"))); // NOI18N
        jMenuItem8.setText("User");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Perhitungan");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1493393979_Finance_finance_caaslculator1.png"))); // NOI18N
        jMenuItem7.setText("Hasil Akhir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonImageReflection2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImageReflection2ActionPerformed
        // TODO add your handling code here:
        if (!h.isVisible()) {
            try {
                jDesktopPanetransparan1.add(h);
                h.show();
                h.setTitle("Home");
                controlhome.getData(h);
                h.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                h.show();
                h.setTitle("Home");
                controlhome.getData(h);
                h.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonImageReflection2ActionPerformed

    private void buttonImageReflection4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImageReflection4ActionPerformed
        // TODO add your handling code here:
        if (!k.isVisible()) {
            try {
                jDesktopPanetransparan1.add(k);
                k.show();
                k.setTitle("Kriteria");
                controlkriteria.getData(k);
                controlkriteria.getDataGlobal(k);
                if (jLabel1.getText().equals("Admin")) {
                    k.jTabbedPane1.setSelectedIndex(0);
                    k.jButton10.setVisible(true);
                } else {
                    k.jTabbedPane1.setSelectedIndex(1);
                    k.jButton10.setVisible(false);
                }
                k.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                k.show();
                k.setTitle("Kriteria");
                controlkriteria.getData(k);
                controlkriteria.getDataGlobal(k);
                if (jLabel1.getText().equals("Admin")) {
                    k.jTabbedPane1.setSelectedIndex(0);
                    k.jButton10.setVisible(true);
                } else {
                    k.jTabbedPane1.setSelectedIndex(1);
                    k.jButton10.setVisible(false);
                }
                k.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonImageReflection4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
//        close();
        int yakin = JOptionPane.showConfirmDialog(this, "Are you Sure Log Out Application ?", "Confirm", JOptionPane.YES_NO_OPTION);
        login o = new login();
        if (yakin == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            o.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void close(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_close
        // TODO add your handling code here:
        int yakin = JOptionPane.showConfirmDialog(this, "Are you Sure Exit Application ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (yakin == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_close

    private void buttonImageReflection5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImageReflection5ActionPerformed
        // TODO add your handling code here:
        if (!s.isVisible()) {
            try {
                jDesktopPanetransparan1.add(s);
                s.show();
                s.setTitle("Subkriteria");
                controlsubkriteria.getDataGlobal(s);
                controlsubkriteria.getData(s);
                if (jLabel1.getText().equals("Admin")) {
                    s.jTabbedPane1.setSelectedIndex(0);
                    s.jButton13.setVisible(true);
                } else {
                    s.jTabbedPane1.setSelectedIndex(1);
                    s.jButton13.setVisible(false);
                }
                s.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                s.show();
                s.setTitle("Subkriteria");
                controlsubkriteria.getDataGlobal(s);
                controlsubkriteria.getData(s);
                if (jLabel1.getText().equals("Admin")) {
                    s.jTabbedPane1.setSelectedIndex(0);
                    s.jButton13.setVisible(true);
                } else {
                    s.jTabbedPane1.setSelectedIndex(1);
                    s.jButton13.setVisible(false);
                }
                s.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonImageReflection5ActionPerformed

    private void buttonImageReflection3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImageReflection3ActionPerformed
        // TODO add your handling code here:
        if (!a.isVisible()) {
            try {
                jDesktopPanetransparan1.add(a);
                a.show();
                a.setTitle("Alternatif");
                controlalternatif.getDataSubkriteria(a);
                controlalternatif.getDataAlternatifSubkriteria(a);
                if (jLabel1.getText().equals("Admin")) {
                    a.jTabbedPane1.setSelectedIndex(0);
                    a.jButton13.setVisible(true);
                } else {
                    a.jTabbedPane1.setSelectedIndex(1);
                    a.jButton13.setVisible(false);
                }
                controlalternatif.getDataGlobal(a);
                a.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                a.show();
                a.setTitle("Alternatif");
                controlalternatif.getDataSubkriteria(a);
                controlalternatif.getDataAlternatifSubkriteria(a);
                if (jLabel1.getText().equals("Admin")) {
                    a.jTabbedPane1.setSelectedIndex(0);
                    a.jButton13.setVisible(true);
                } else {
                    a.jTabbedPane1.setSelectedIndex(1);
                    a.jButton13.setVisible(false);
                }
                controlalternatif.getDataGlobal(a);
                a.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonImageReflection3ActionPerformed

    private void buttonImageReflection6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImageReflection6ActionPerformed
        // TODO add your handling code here:
        if (!p.isVisible()) {
            try {
                jDesktopPanetransparan1.add(p);
                p.show();
                p.setTitle("Perhitungan Akhir");
                controlperhitungan.getData(p);
                p.jTabbedPane1.setSelectedIndex(0);
                p.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                p.show();
                p.setTitle("Perhitungan Akhir");
                controlperhitungan.getData(p);
                p.jTabbedPane1.setSelectedIndex(0);
                p.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonImageReflection6ActionPerformed

    private void buttonImageReflection1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImageReflection1ActionPerformed
        // TODO add your handling code here:
        if (!u.isVisible()) {
            try {
                jDesktopPanetransparan1.add(u);
                u.show();
                u.setTitle("User");
                controluser.getData(u);
                u.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                u.show();
                u.setTitle("User");
                controluser.getData(u);
                u.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonImageReflection1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        buttonImageReflection2ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        buttonImageReflection4ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        buttonImageReflection5ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        buttonImageReflection3ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        buttonImageReflection1ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        buttonImageReflection6ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    public void close() {
        WindowEvent event = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(event);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.glass.ButtonImageReflection buttonImageReflection1;
    public usu.widget.glass.ButtonImageReflection buttonImageReflection2;
    private usu.widget.glass.ButtonImageReflection buttonImageReflection3;
    private usu.widget.glass.ButtonImageReflection buttonImageReflection4;
    private usu.widget.glass.ButtonImageReflection buttonImageReflection5;
    private usu.widget.glass.ButtonImageReflection buttonImageReflection6;
    private com.ta.johan.background.JDesktopPaneGambarHome jDesktopPaneGambarHome1;
    private com.ta.johan.background.JDesktopPanetransparan jDesktopPanetransparan1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
